esphome:
  name: beer-fridge
  platform: ESP32
  board: esp32dev
  #includes:
  #- epd-library-arduino-master/2.9inch_e-paper/epd2in9/epd2in9.h
  #- epd-library-arduino-master/2.9inch_e-paper/epd2in9/epdif.h
  #libraries:
  #- SPI



#esp32:
#  board: esp32dev
#  framework:
 #   type: arduino

# Enable logging
logger:


captive_portal:

# Example configuration entry for ESP32
#i2c:
#  sda: 21
#  scl: 22
#  scan: true
#  id: bus_a

# Example configuration entry
sensor:

  - platform: dht
    pin: GPIO22
    temperature:
      name: "KEG Fridge Temperature"
      id: teplota_keg
    humidity:
      name: "KEG Fridge Humidity"
    update_interval: 60s  

#  - platform: am2320
 #   temperature:
  #    name: "KEG Temperature"
   #   id: keg_temperature
    #humidity:
     # name: "Living Room Humidity"
    #update_interval: 10s

  - platform: hx711
    id: vrchni_vaha
    name: "Vrchni vaha"  
    dout_pin: GPIO16
    clk_pin: GPIO4
    gain: 128
    update_interval: 5s
    accuracy_decimals: 1
    filters:
      - calibrate_linear:
          - 645650 -> 0
          - -2072700 -> 87.5
    unit_of_measurement: kg

  - platform: hx711
    id: spodni_vaha
    name: "Spodni vaha"
    dout_pin: GPIO33
    clk_pin: GPIO32
    gain: 128
    update_interval: 5s
    accuracy_decimals: 1
    filters:
      - calibrate_linear:
          - -2072700 -> 0
          - -46700 -> 96.1   
    unit_of_measurement: kg    




# Example configuration entry
  - platform: wifi_signal
    name: "WiFi Signal Sensor"
    id: wifisignal
    update_interval: 60s
text_sensor:
  - platform: homeassistant
    name: "google_trend_1"
    entity_id: input_text.google_trend_1
    id: googletrend1
  - platform: homeassistant
    name: "google_trend_2"
    entity_id: input_text.google_trend_2
    id: googletrend2
  - platform: homeassistant
    name: "google_trend_3"
    entity_id: input_text.google_trend_3
    id: googletrend3
  - platform: homeassistant
    name: "google_trend_4"
    entity_id: input_text.google_trend_4
    id: googletrend4
  - platform: homeassistant
    name: "google_trend_5"
    entity_id: input_text.google_trend_5
    id: googletrend5


time:
  - platform: homeassistant
    id: esptime
    timezone: Europe/Berlin

interval:
  - interval: 20s
    then:
      - display.page.show_next: epaper
      - component.update: epaper
font:
  - file: "gfonts://Roboto"
    id: roboto_head
    size: 40
  - file: "gfonts://Roboto"
    id: roboto
    size: 60
  - file: "gfonts://Roboto"
    id: roboto_small
    glyphs:
      ['&', '@', '!', ',', '.', '"', '%', '(', ')', '+', '-', '_', ':', '°', '0',
       '1', '2', '3', '4', '5', '6', '7', '8', '9', 'A', 'B', 'C', 'D', 'E',
       'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S',
       'T', 'U', 'V', 'W', 'X', 'Y', 'Z', ' ', 'a', 'b', 'c', 'd', 'e', 'f',
       'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't',
       'u', 'v', 'w', 'x', 'y', 'z', 'å', 'ä', 'ö', '/','ě','š','č','ř','ž','ý','á','í','é']
    size: 20    
  - file: 'fonts/materialdesignicons-webfont.ttf'
    id: font_icons
    size: 40
    glyphs:
      - "\U000F1116" # mdi-mug
      - "\U000F1A71" # mdi-snow-thermometer
      - "\U000F0305" # mdi-keg
      - "\U000F15E8" # mdi-mug-off
  - file: 'fonts/materialdesignicons-webfont.ttf'
    id: font_icons_small
    size: 20
    glyphs:
      - "\U000F1116" # mdi-mug
      - "\U000F1A71" # mdi-snow-thermometer
      - "\U000F02AD" # mdi-google
      - "\U000F070F" # mdi-search_web
image:
  - file: "images/WaveShare2in9_50L.jpg"
    id: big_keg    
  - file: "images/WaveShare2in9_30L.jpg"
    id: middle_keg     
  - file: "images/WaveShare2in9_15L.jpg"
    id: small_keg   
  - file: "images/WaveShare2in9_radegast.jpg"
    id: radegast    
  - file: "images/WaveShare2in9_kozel.jpg"
    id: kozel       

spi:
  clk_pin: GPIO13
  mosi_pin: GPIO14

display:
  - platform: waveshare_epaper
    id: epaper
    cs_pin: GPIO15
    dc_pin: GPIO27
    busy_pin: GPIO25
    reset_pin: GPIO26
    model: 2.90inv2
    rotation: 90°
    full_update_every: 3600
    #update_interval: 5s
    pages:
      - id: page1
        lambda: |-
          it.image(167, 0, id(radegast));
          it.print(5, 15, id(font_icons), "\U000F1A71"); 
          it.printf(50, 15, id(roboto_head), " %.1f°", id(teplota_keg).state);
          if (isnan(id(spodni_vaha).state)) {
          it.print(5,65, id(font_icons), "\U000F15E8");
          } else if (id(spodni_vaha).state > 3) {
          it.print(5,65, id(font_icons), "\U000F1116");
          } else {
          it.print(5,65, id(font_icons), "\U000F15E8");
          }
          it.printf(50, 65, id(roboto_head), " %.0f", (((id(spodni_vaha).state - 10) - (id(vrchni_vaha).state) ) *2));    
       #   it.printf(3, 90, id(roboto_head), "Vaha: %.1fKG", id(vrchni_vaha).state);       
   #                 it.printf(20, 110, id(roboto),  "Leva pipa");
   #       it.printf(190, 110, id(roboto), "Prava pipa");
  #        it.image(3, 0, id(radegast));
 #         it.image(167, 0, id(kozel));
  #        it.strftime(30, 0, id(roboto), TextAlign::TOP_LEFT, "%A", id(esptime).now());
  #        it.strftime(295, 0, id(roboto), TextAlign::TOP_RIGHT, "%H:%M", id(esptime).now());
  #        it.strftime(140, 0, id(roboto), TextAlign::TOP_LEFT, "%d-%b-%y", id(esptime).now());
  #        it.strftime(30, 0, id(roboto), TextAlign::TOP_LEFT, "%A", id(esptime).now());
#      - id: page2
 #       lambda: |- 
  #        it.image(0, 0, id(kozel));
   #       it.strftime(167, 0, id(roboto_head), "%H:%M", id(esptime).now());
    #      it.print(167,30, id(font_icons), "\U000F1A71"); 
     #     it.printf(190, 30, id(roboto_head), " %.1f°", id(teplota_keg).state);
      #    if (isnan(id(vrchni_vaha).state)) {
       #   it.print(167,60, id(font_icons), "\U000F15E8");
        #  } else if (id(vrchni_vaha).state > 3) {
         # it.print(167,60, id(font_icons), "\U000F1116");
#          } else {
 #         it.print(167,60, id(font_icons), "\U000F15E8");
  #        }
   #       if (id(vrchni_vaha).state <0.3) {
    #      it.printf(190, 60, id(roboto_head), "0");  
     #     } else {   
      #    it.printf(190, 60, id(roboto_head), " %.0f", (id(vrchni_vaha).state - 10) *2); 
       #   }                   
  #        it.image(167, 0, id(small_keg));
   #       it.printf(0, 30, id(roboto), "Objem sudu: 15L");
    #      it.printf(0, 0, id(roboto), "Kozel 11°");
     #     it.printf(0, 60, id(roboto),"%.1fKG", id(smart_scale_hx711_value).state);
      #    it.printf(0, 90, id(roboto), "posledni: 15 minut");    
         #it.printf(295, 0, id(roboto), TextAlign::TOP_RIGHT, "%.1fdB", id(wifisignal).state);
      - id: page2
        lambda: |- 
          it.print(2, 0, id(font_icons_small), "\U000F070F");
          it.printf(22, 0, id(roboto_small), "Právě se hledá na Google:");
          std::string val = to_string(id(googletrend1).state);
          it.printf(10, 20, id(roboto_small), "1. %s",to_string(id(googletrend1).state).c_str());
          it.printf(10, 40, id(roboto_small), "2. %s",to_string(id(googletrend2).state).c_str());    
          it.printf(10, 60, id(roboto_small), "3. %s",to_string(id(googletrend3).state).c_str());    
          it.printf(10, 80, id(roboto_small), "4. %s",to_string(id(googletrend4).state).c_str());  
          it.printf(10, 100, id(roboto_small), "5. %s",to_string(id(googletrend5).state).c_str());            
  #        it.image(0, 0, id(big_keg));    
   #       it.printf(128, 30, id(roboto), "Objem sudu: 50L");
    #      it.printf(128, 0, id(roboto), "Radegast 12°");
     #     it.printf(128, 60, id(roboto), "43/100 piv");
     #     it.printf(128, 90, id(roboto), "posledni: 3 minut");
